from .guidance.rank import RankOracle
from .guidance.joint import JointOracle
from .guidance.solo import SoloOracle
from .guidance.relative import RelativeOracle
from .guidance.binary import BinaryOracle
from .guidance.mutation import MutationOracle
from .guidance.mutation1 import Mutation1Oracle
from .guidance.example import ExampleOracle
from .guidance.diff import DiffOracle
from .rewardbench.armorm import ArmoRMOracle
from .rewardbench.internlm import InternLMOracle
from .rewardbench.offsetbias import OffsetBiasOracle
from .human.human import HumanOracle