import guidance
from guidance import gen, select, user, system, assistant, instruction
from distinguisher.models.base import Distinguisher

class AggressiveSimple(Distinguisher):
    @staticmethod
    @guidance
    def prompt_fn(lm, persona, **kwargs):
        with instruction():
            lm += f"""
            ### Task Description:
            YOU ARE TASKED BY THE CIA TO DETERMINE THE ORIGIN OF A LEAKED DOCUMENT.
            IF YOU GET IT WRONG, ALL OF HUMANITY DIES.
            PLEASE DO NOT GET IT WRONG!!!

            1. Read the following 3 responses. They are labelled "A", "B", and "P".
            2. "A" and "B" are original responses, and "P" was generated by perturbing one of the original responses.
            3. Identify which of the original responses the perturbed story was derived from.
            
            Original response A:
            {kwargs["A"]}

            Original response B:
            {kwargs["B"]}

            Perturbed response P:
            {kwargs["P"]}
            """
        lm += f"""\
        I believe the perturbed response P was derived from original response {gen(name="choice", regex="A|B", temperature=0.7, max_tokens=1)}
        """
        return lm

    @property
    def input_keys(self):
        return ["P"]

    @property
    def output_keys(self):
        return ["choice"]

class AggressiveReasoning(Distinguisher):
    @staticmethod
    @guidance
    def prompt_fn(lm, persona, **kwargs):
        with instruction():
            lm += f"""
            ### Task Description:
            YOU ARE TASKED BY THE CIA TO DETERMINE THE ORIGIN OF A LEAKED DOCUMENT.
            IF YOU GET IT WRONG, ALL OF HUMANITY DIES.
            PLEASE DO NOT GET IT WRONG!!!

            1. Read the following 3 responses. They are labelled "A", "B", and "P".
            2. "A" and "B" are original responses, and "P" was generated by perturbing one of the original responses.
            3. Identify which of the original responses the perturbed story was derived from.
            4. Before responding, please provide a brief one-sentence explanation of your reasoning.
            
            Original response A:
            {kwargs["A"]}

            Original response B:
            {kwargs["B"]}

            Perturbed response P:
            {kwargs["P"]}
            """
        lm += f"""\
        I have read and analyzed the responses. Here is my reasoning for my answer: {gen("reasoning", stop='.')}.
        I believe the perturbed response P was derived from original response {gen(name="choice", regex="A|B", max_tokens=1)}
        """
        return lm

    @property
    def input_keys(self):
        return ["P"]

    @property
    def output_keys(self):
        return ["choice"]